### ISSUE TITLE
Ignore URL Patterns

### ISSUE THREAD

**Issue by pyvelkov** [chrispinkney/hes-dead-jim#26]
Hey Chris,
I would like to add a ignore URL patterns feature to your program. 
Let me know if that would be alright!

Thanks,
Plamen

**Comment by chrispinkney** [comment]
Hi Plamen, I don't know what you mean, could you elaborate?

**Comment by pyvelkov** [comment]
I would like to add a command line argument where it would take a file and ignore certain urls specified in that file.
i.e. 
`hdj.py --ignore ignore-urls.txt index.html`

**Comment by chrispinkney** [comment]
Ohhhh, you mean for lab 4. Sure go ahead.

**Comment by chrispinkney** [comment]
Closed in 1a6c3fdb6a5c2090ebc5cab66dc31d9cfcb943ad.
